### PR TITLE
Switch to np.array type by default

### PR DESCRIPTION
**Pull request by jcarpent**
Solving #87.

### CODE REVIEW

**Comment by gabrielebndn** [comment]
You are aware Pinocchio isn't 100% ready?
I can fix it in one or two days

**Comment by jcarpent** [comment]
I will proceed to a new release today or one the following days.

**Comment by gabrielebndn** [comment]
May I suggest increasing the major version for next release? After all, it is a big change which will likely break lots of stuff for users who are not ready

**Comment by jmirabel** [comment]
I think this was what we decided in #87

**Pull request merged**
