### PR TITLE
Copy std-vector and std-map from Pinocchio

### LINKED ISSUE #324: Proposal: port StdVectorPythonVisitor from Pinocchio's bindings
The header is here: https://github.com/stack-of-tasks/pinocchio/blob/devel/bindings/python/utils/std-vector.hpp (or a more recent version).
I recently suggested moving/copying the **`StdVectorPythonVisitor`** template from Pinocchio's bindings upstream to this repo, so that downstream packages don't have to import or copy the header from Pinocchio.

We could also import the **`StdContainerFromPythonList`** template.

What do we think of this ? I could do it if we choose to go ahead with it.

### PR DESCRIPTION
**Pull request by ManifoldFR**
I recovered the history using `git-filter-repo`, squashed and rebased it into a single big commit before merging the files' history into eigenpy.

**TODO**

* Include the `utils/copyable.hpp` header from Pinocchio
* Include the relevant tests

Closes #324

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Review by jcarpent — CHANGES_REQUESTED** [review]
@ManifoldFR Thanks a lot for this PR.
Could you remove aligned_vector, which is not useful to have I do think?

**Comment by ManifoldFR** [comment]
> @ManifoldFR Thanks a lot for this PR. Could you remove aligned_vector, which is not useful to have I do think?

Ok, will do so

**Comment by ManifoldFR** [comment]
Rebased on devel.

**Comment by fabinsch** [comment]
Now it should be fixed. I will manually squash my commits and force push.

**Comment by jcarpent** [comment]
Nice work @ManifoldFR and @fabinsch. Thanks a lot.

**Pull request merged**
