### PR TITLE
Fix install directory, address #116

### PR DESCRIPTION
**Pull request by wxmerkt**
The issue underlying #116 is that:

1. The library gets installed to `${CMAKE_INSTALL_PREFIX}/lib`
2. However, the use of `GNUInstallDirs` inside the `cmake/base.cmake` sets the variable defining what gets set in the `pkg-config` template to use the `FULL` variables. These get set to include the prefix on some platforms (and old versions of debhelper). 
3. As a result there is a mismatch between what the `eigenpy.pc` says for where the library and pkg-config files are and where they actually get installed.

This took quite some time to debug...

### CODE REVIEW

**Comment by wxmerkt** [comment]
@nim65s Will this be fine for you guys? I reckon this issue may lurk in other cmakemodules depending projects as well...

**Comment by jcarpent** [comment]
@wxmerkt Thanks a lot for fixing this annoying bug.

**Comment by nim65s** [comment]
If it fixes the build for you, and if that's the right way to do it, then it's ok for me. 
For robotpkg, I don't think it will change something, and if it does, I will be able to override it anyway :)

**Comment by nim65s** [comment]
(i would have preferred `lib` to `${CMAKE_INSTALL_FULL_INCLUDEDIR}`, but this is not relevant for now.)

**Comment by jcarpent** [comment]
@nim65s Thanks for your feedback.

**Comment by wxmerkt** [comment]
Thank you guys! @jcarpent Can you please increment the package.xml and make a new release? :-)

**Pull request merged**
