### PR TITLE
test python 2/3 ubuntu 18/20/22

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

This add CI jobs to run unit tests in multiple Ubuntu / Python configuration.
It is currently showing a segfault with Ubuntu 18.04, Python 3.6, Boost 1.65, and Numpy 1.13.

### CODE REVIEW

**Review by jcarpent — DISMISSED** [review]

**Comment by jcarpent** [comment]
@nim65s Could you prepare a docker container for debugging purposes?

**Comment by nim65s** [comment]
Sure:

```Dockerfile
FROM ubuntu:18.04

RUN --mount=type=cache,sharing=locked,target=/var/cache/apt \
    --mount=type=cache,sharing=locked,target=/var/lib/apt \
    apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -qqy \
    build-essential \
    cmake \
    git \
    libboost-all-dev \
    libeigen3-dev \
    python3-numpy

WORKDIR /src
RUN git clone --recursive -j4 -b devel https://github.com/stack-of-tasks/eigenpy

WORKDIR /src/eigenpy/build
RUN cmake -DPYTHON_EXECUTABLE=$(which python3) ..

RUN make -sj12
#RUN make test
```

Available with `docker run --rm -it gepetto/utils:eigenpy-3.6`

**Comment by nim65s** [comment]
NB: it is not always triggered. `py-user-type` segfault most of the times, but not always. And I think I also saw a `user_type` segfault, but I'm not sure.

**Comment by nim65s** [comment]
ROS-CI foxy fails with unrelated:
```
  CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCXXCompiler.cmake:53 (message):
    The C++ compiler
  
      "/usr/lib/ccache/c++"
  
    is not able to compile a simple test program.
  
 […]
      ccache: error: Failed to create directory /home/buildfarm/.ccache/tmp: Permission denied

**Comment by jcarpent** [comment]
@wxmerkt It seems there is an issue with the ROS CI. Do you know the origin?

**Comment by wxmerkt** [comment]
Hi @jcarpent - I just got back and will look into this

**Comment by jcarpent** [comment]
@wxmerkt, in [a083857](https://github.com/stack-of-tasks/eigenpy/pull/341/commits/a0838570533edf1f5755bef70268c4b1d7a41706), I've changed the commit id of the industrial_ci and it seems the bug is related to a recent change here https://github.com/ros-industrial/industrial_ci/commit/116e03719068140261fe958690e1196e7d330419. Do you see an option to revert the change?

**Review by jcarpent — APPROVED** [review]

**Comment by wxmerkt** [comment]
Thanks for investigating and the fix! Let's leave it with your fix for now and try reverting back to master once upstream gets fixed

**Pull request merged**
