### PR TITLE
Restoring previous removed code

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jmirabel** [comment]
For your info, 657208e makes the SEGV on exit reappearing. Running script from #35 several yields a SEGV from time to time (3 out of 10 in my case).

**Comment by jcarpent** [comment]
@jmirabel The behavior you mentioned is really weird, don't you think so?
Anyway, I will just comment those lines, hoping that the behavior you've mentioned will disappear.

**Comment by jmirabel** [comment]
Yes, it is. Something does bad things with the references on some part of NumPy. I have no idea how to find who... Maybe valgrind can help us.

**Comment by jcarpent** [comment]
By the way, I did not get this behavior on my computer. Are sure that you're working with the latest devel version?

**Comment by jmirabel** [comment]
Yes, I am sure. With Python 3.5.2 and NumPy 1.11.0.
I have to run it several times to get a SEGV. It is not consistent over
runs.
```python
import numpy, matrix
import numpy as np

m = np.reshape(range(64), (8, 8))
a = matrix.reflex(m, False)
print('end of script')
```

**Comment by jcarpent** [comment]
I've tried several times and I don't get this issue with numpy 1.16 and Python 3.7.3

**Comment by jmirabel** [comment]
Me too as mentioned here: https://github.com/stack-of-tasks/eigenpy/issues/35#issuecomment-482041591

**Comment by jcarpent** [comment]
Yes, but without your fix, it was not working. I had a segfault with Python 3.7.3 and NumPy 1.16.
But, I don't see your point concerning the restore commit of "asmatrix".

**Comment by jmirabel** [comment]
My point is that I have a SEGV with 657208e and I don't have a SEGV when I revert it.

**Pull request merged**
