### PR TITLE
Add EIGENPY_SITELIB_ROOT to customize sitelib install location.

### PR DESCRIPTION
**Pull request by seanyen**
This is a pull request to port a patch from `eigenpy-feedstock`. In `conda` configuration, the Python modules and the native library doesn't share the same install prefix. Hope we can add some flexibility to customize where to place Python modules in `CMake` files.

### CODE REVIEW

**Comment by seanyen** [comment]
There was a `travis-ci` build timeout so I trigger another round.

**Comment by jcarpent** [comment]
OK. You can also do a `git commit --amend` to avoid a new commit ;)

**Comment by jcarpent** [comment]
@seanyen Do you need a new release now?

**Comment by nim65s** [comment]
There is also a "Restart build" button, but I guess it is not accessible by everyone.

**Comment by seanyen** [comment]
@jcarpent if you have bandwidth for a new release, that would be fantastic. I really appreciated your time. :)

I didn't know the `git commit --amend` trick. Every day I learned something new.

**Comment by jcarpent** [comment]
@seanyen Can you handle the conda forge?

**Comment by gabrielebndn** [comment]
The easiest way to trigger a new CI is to close the PR and reopen it

**Comment by seanyen** [comment]
> @seanyen Can you handle the conda forge?

Sure, I am on it now.

**Comment by wxmerkt** [comment]
> There is also a "Restart build" button, but I guess it is not accessible by everyone.

It is accessible as soon as you login.

**Pull request merged**
