### PR TITLE
Fix int conversion

### LINKED ISSUE #449: SimplicialLDLT Error on Windows
SimplicialLDLT gives an error on windows (installed from conda-forge)

I created a fresh environment and installed eigenpy.

`micromamba install eigenpy -n eigenpy -c conda-forge`

```
Name                   Version       Build                  Channel
---------------------------------------------------------------------------
  bzip2                  1.0.8         hcfcfb64_5             conda-forge
  ca-certificates        2024.2.2      h56e8100_0             conda-forge
  eigen                  3.4.0         h91493d7_0             conda-forge
  eigenpy                3.4.0         py312h0bfd76e_0        conda-forge
  intel-openmp           2024.0.0      h57928b3_49841         conda-forge
  libblas                3.9.0         21_win64_mkl           conda-forge
  libboost               1.82.0        h65993cd_6             conda-forge
  libboost-devel         1.82.0        h91493d7_6             conda-forge
  libboost-headers       1.82.0        h57928b3_6             conda-forge
  libboost-python        1.82.0        py312h4f1204c_6        conda-forge
  libboost-python-devel  1.82.0        py312hd42ba9a_6        conda-forge
  libcblas               3.9.0         21_win64_mkl           conda-forge
  libexpat               2.6.2         h63175ca_0             conda-forge
  libffi                 3.4.2         h8ffe710_5             conda-forge
  libhwloc               2.9.3         default_haede6df_1009  conda-forge
  libiconv               1.17          hcfcfb64_2             conda-forge
  liblapack              3.9.0         21_win64_mkl           conda-forge
  libsqlite              3.45.2        hcfcfb64_0             conda-forge
  libxml2                2.12.6        hc3477c8_0             conda-forge
  libzlib                1.2.13        hcfcfb64_5             conda-forge
  mkl                    2024.0.0      h66d3029_49657         conda-forge
  numpy                  1.26.4        py312h8753938_0        conda-forge
  openssl                3.2.1         hcfcfb64_0             conda-forge
  pip                    24.0          pyhd8ed1ab_0           conda-forge
  pthreads-win32         2.9.1         hfa6e2cd_3             conda-forge
  python                 3.12.2        h2628c8c_0_cpython     conda-forge
  python_abi             3.12          4_cp312                conda-forge
  scipy                  1.12.0        py312h8753938_2        conda-forge
  setuptools             69.2.0        pyhd8ed1ab_0           conda-forge
  tbb                    2021.11.0     h91493d7_1             conda-forge
  tk                     8.6.13        h5226925_1             conda-forge
  tzdata                 2024a         h0c530f3_0             conda-forge
  ucrt                   10.0.22621.0  h57928b3_0             conda-forge
  vc                     14.3          hcf57466_18            conda-forge
  vc14_runtime           14.38.33130   h82b7239_18            conda-forge
  vs2015_runtime         14.38.33130   hcb4865c_18            conda-forge
  wheel                  0.42.0        pyhd8ed1ab_0           conda-forge
  xz                     5.2.6         h8d14728_0             conda-forge
  zstd                   1.5.5         h12be248_0             conda-forge
```

Then I tried to run the unittest for SimplicialLDLT
```
import numpy as np
from scipy.sparse import csc_matrix

import eigenpy

dim = 100
rng = np.random.default_rng()

A = rng.random((dim, dim))
A = (A + A.T) * 0.5 + np.diag(10.0 + rng.random(dim))

A = csc_matrix(A)

ldlt = eigenpy.SimplicialLDLT(A)
```

which resulted in the following error:
`TypeError: No registered converter was able to produce a C++ rvalue of type class Eigen::Matrix<int,-1,1,0,-1,1> from this Python object of type numpy.ndarray
`

The issue seems to be only present on Windows.
On my macbook (osx-arm64) everything works as expected.

### PR DESCRIPTION
**Pull request by jorisv**
Close #449

# Changes

- Support new primitive type (char, int8_t, uint8_t, int16_t, uint16_t, uint32_t, uint64_t)
- Support conversion between signed <-> unsigned integers
- Support conversion between complex numbers
- Fix `int` management on Windows (NPY_INT32 is NPY_LONG, then NPY_INT is never used on Windows)
- Fix `long long` management on Mac (NPY_LONGLONG and NPY_LONG are both 64 bits and `long` and `long long` are the same type on Mac, then there is only one C++ type that must old two different dtype)
- Remove casting when converting from Eigen scalar to Numpy scalar.
  This should not remove any functionality since Numpy array are created from the Eigen scalar type

# Comparison between numpy dtype in Linux/Mac/Windows
Table comparison

# Notes

- Linux is the only OS to have a 128 bits `long double`
- Windows Int32DType is NPY_LONG (7) where is NPY_INT on Mac/Linux (5)
- Windows Int64DType is NPY_LONGLONG (9) where is NPY_LONG on Mac/Linux (7)
- Windows `long` is 32 bits where is 64 bits on Mac/Linux
- Windows `long` is not the same type than `int` and `int32_t` (but it's also a 32 bits integer)
- Linux `long long` is not the same type than `long` and `int64_t` (but it's also a 64 bits integer)
- Mac `long` is not the same type than `int64_t` (but it's also a 64 bits integer)
- On Windows NPY_INT and NPY_LONG target the same size
  - This is an issue because numpy will store python int as NPY_LONG
  - The solution is to convert NPY_LONG to C++ `int` and `long`
  - NPY_INT on Windows look like deprecated (impossible to create it from python without calling a deprecated function)
- On Mac NPY_LONGLONG and NPY_LONG target the same size
  - This is an issue because `long` and `long long` are the same C++ type
  - We can't support NPY_LONGLONG because we can only map 1 numpy type to 1 C++ type

# TODO

- [x] Fix on all system
- [x] Manage mapping of 1 C++ type to many numpy type (via promotion)
- [x] Manage type promotion
- [x] Manage tensor and sparse ?
  - [x] Factorize code between tensor and matrix
- [x] Fix changelog
- [x] Add PR ref in the code
- [x] Reactivate scalar -> complex conversion

# Linux table

|Type            |NPY_TYPES|itemsize|c++                      |
|----------------|---|--------|-------------------------|
|BoolDType       |0  |1       |bool                     |
|ByteDType       |1  |1       |char/int8_t              |
|CLongDoubleDType|16 |32      |std::complex<long double>|
|Complex128DType |15 |16      |std::complex<double>     |
|Complex64DType  |14 |8       |std::complex<float>      |
|Float16DType    |23 |2       |None                     |
|Float32DType    |11 |4       |float                    |
|Float64DType    |12 |8       |double                   |
|Int16DType      |3  |2       |short/int16_t            |
|Int32DType      |5  |4       |int/int32_t              |
|Int64DType      |7  |8       |long/int64_t             |
|Int8DType       |1  |1       |char/int8_t              |
|IntDType        |5  |4       |int/int32_t              |
|LongDType       |7  |8       |long/int64_t             |
|LongDoubleDType |13 |16      |long double              |
|LongLongDType   |9  |8       |long long                |
|ObjectDType     |17 |8       |None                     |
|ShortDType      |3  |2       |short/int16_t            |
|UByteDType      |2  |1       |unsigned char/uint8_t    |
|UInt16DType     |4  |2       |unsigned short/uint16_t  |
|UInt32DType     |6  |4       |unsigned int/uint32_t    |
|UInt64DType     |8  |8       |unsigned long/uint64_t   |
|UInt8DType      |2  |1       |unsigned char/uint8_t    |
|UIntDType       |6  |4       |unsigned int/uint32_t    |
|ULongDType      |8  |8       |unsigned long/uint64_t   |
|ULongLongDType  |10 |8       |unsigned long long       |
|UShortDType     |4  |2       |unsigned short/uint16_t  |

# Mac table

|Type            |NPY_TYPES|itemsize|c++                      |
|----------------|---|--------|-------------------------|
|BoolDType       |0  |1       |bool                     |
|ByteDType       |1  |1       |char/int8_t              |
|CLongDoubleDType|16 |16      |std::complex<long double>|
|Complex128DType |15 |16      |std::complex<double>     |
|Complex64DType  |14 |8       |std::complex<float>      |
|Float16DType    |23 |2       |None                     |
|Float32DType    |11 |4       |float                    |
|Float64DType    |12 |8       |double                   |
|Int16DType      |3  |2       |short/int16_t            |
|Int32DType      |5  |4       |int/int32_t              |
|Int64DType      |7  |8       |long/int64_t             |
|Int8DType       |1  |1       |char/int8_t              |
|IntDType        |5  |4       |int/int32_t              |
|LongDType       |7  |8       |long/int64_t             |
|LongDoubleDType |13 |8       |long double              |
|LongLongDType   |9  |8       |long long                |
|ObjectDType     |17 |8       |None                     |
|ShortDType      |3  |2       |short/int16_t            |
|UByteDType      |2  |1       |unsigned char/uint8_t    |
|UInt16DType     |4  |2       |unsigned short/uint16_t  |
|UInt32DType     |6  |4       |unsigned int/uint32_t    |
|UInt64DType     |8  |8       |unsigned long/uint64_t   |
|UInt8DType      |2  |1       |unsigned char/uint8_t    |
|UIntDType       |6  |4       |unsigned int/uint32_t    |
|ULongDType      |8  |8       |unsigned long/uint64_t   |
|ULongLongDType  |10 |8       |unsigned long long       |
|UShortDType     |4  |2       |unsigned short/uint16_t  |

# Windows table

|Type            |NPY_TYPES|itemsize|c++                      |
|----------------|---|--------|-------------------------|
|BoolDType       |0  |1       |bool                     |
|ByteDType       |1  |1       |char/int8_t              |
|CLongDoubleDType|16 |16      |std::complex<long double>|
|Complex128DType |15 |16      |std::complex<double>     |
|Complex64DType  |14 |8       |std::complex<float>      |
|Float16DType    |23 |2       |None                     |
|Float32DType    |11 |4       |float                    |
|Float64DType    |12 |8       |double                   |
|Int16DType      |3  |2       |short/int16_t            |
|Int32DType      |7  |4       |int/int32_t              |
|Int64DType      |9  |8       |long/int64_t             |
|Int8DType       |1  |1       |char/int8_t              |
|IntDType        |5  |4       |int/long/int32_t         |
|LongDType       |7  |4       |int/long/int32_t         |
|LongDoubleDType |13 |8       |long double              |
|LongLongDType   |9  |8       |long long                |
|ObjectDType     |17 |8       |None                     |
|ShortDType      |3  |2       |short/int16_t            |
|UByteDType      |2  |1       |unsigned char/uint8_t    |
|UInt16DType     |4  |2       |unsigned short/uint16_t  |
|UInt32DType     |8  |4       |unsigned int/uint32_t    |
|UInt64DType     |10 |8       |unsigned long/uint64_t   |
|UInt8DType      |2  |1       |unsigned char/uint8_t    |
|UIntDType       |6  |4       |unsigned int/uint32_t    |
|ULongDType      |8  |4       |unsigned long/uint64_t   |
|ULongLongDType  |10 |8       |unsigned long long       |
|UShortDType     |4  |2       |unsigned short/uint16_t  |

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Review by jcarpent — APPROVED** [review]
@jorisv Amazing. Thanks a lot for the big fix which will help to better support Windows applications

**Review by ManifoldFR — DISMISSED** [review]
scrumptious

**Review by ManifoldFR — APPROVED** [review]
Thanks for the hard work @jorisv !!

**Pull request merged**
