### PR TITLE
Template specialization for sized Eigen::{MatrixBase,EigenBase}

### PR DESCRIPTION
**Pull request by jcarpent**
@duburcqa Could try this potential fix?

### CODE REVIEW

**Comment by jcarpent** [comment]
Related to #156.

**Comment by jcarpent** [comment]
@duburcqa I've fixed a bug coming from a template specialization for Eigen::MatrixBase types. Now everything should work fine.

**Comment by jcarpent** [comment]
@nim65s I will make a new release of EigenPy, could you please update robotpkg then?

**Comment by duburcqa** [comment]
Yes sure no problem ! It would be perfect

**Comment by nim65s** [comment]
@jcarpent : can do.

**Pull request merged**
