### PR TITLE
Python 3 tests & CI

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

This PR:
- upgrades python tests, to allow them to pass in python 2 & 3
- enables them in travis-ci
- adds gitlab-ci for the gepetto buildfarm
- shows that there are random segfaults with python 3 when the python interpreter is exiting (cf. #35)

### CODE REVIEW

**Comment by nim65s** [comment]
When I say this is random:
- works here: https://travis-ci.org/nim65s/eigenpy/builds/382667362
- doesn't there: https://travis-ci.org/stack-of-tasks/eigenpy/builds/384641394

**Comment by nim65s** [comment]
I updated this PR, but it now has to wait for https://github.com/jrl-umi3218/jrl-cmakemodules/pull/137

**Comment by jcarpent** [comment]
I just merged jrl-umi3218/jrl-cmakemodules#137. Can you update your PR accordingly?

**Comment by nim65s** [comment]
@jcarpent This PR has been updated, but we still have to address #35

**Comment by nim65s** [comment]
I think that we have already spent too much time on #35, while the workaround can be to drop support for python 3 on systems older than ubuntu bionic (18.04), and just merge this PR.

**Comment by jcarpent** [comment]
Ok. I do agree. I will merge now. Thanks for this nice job.

**Pull request merged**
